-- ============================================================
-- Smivo — Dynamic Categories Migration
-- ============================================================
-- Removes the hardcoded CHECK constraint on listings.category
-- so that categories are fully driven by the school_categories
-- table and can be managed via the Admin Dashboard without
-- code changes.
--
-- Also replaces the old 7 categories with the new set and
-- updates the seed_school_defaults() RPC.
-- ============================================================


-- ─── 1. Drop the hardcoded CHECK constraint ───────────────────
-- NOTE: The constraint name was auto-generated by Postgres during
-- CREATE TABLE. We look it up dynamically to be safe.

DO $$
DECLARE
  constraint_name text;
BEGIN
  SELECT cc.conname INTO constraint_name
  FROM pg_constraint cc
  JOIN pg_class c ON cc.conrelid = c.oid
  WHERE c.relname = 'listings'
    AND cc.contype = 'c'
    AND pg_get_constraintdef(cc.oid) ILIKE '%category%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.listings DROP CONSTRAINT %I', constraint_name);
    RAISE NOTICE 'Dropped constraint: %', constraint_name;
  ELSE
    RAISE NOTICE 'No category CHECK constraint found — already removed.';
  END IF;
END $$;


-- ─── 2. Replace school_categories for Smith College ───────────
-- Delete old categories and insert the new set.

DELETE FROM public.school_categories
WHERE school_id = (SELECT id FROM public.schools WHERE slug = 'smith');

INSERT INTO public.school_categories (school_id, slug, name, icon, display_order)
SELECT s.id, v.slug, v.name, v.icon, v.display_order
FROM (VALUES
  ('dorm',            'Dorm',            'bed',            1),
  ('kitchen',         'Kitchen',         'kitchen',        2),
  ('self_care',       'Self-care',       'spa',            3),
  ('food',            'Food',            'lunch_dining',   4),
  ('study_supplies',  'Study Supplies',  'menu_book',      5),
  ('sports',          'Sports',          'sports_soccer',  6),
  ('other',           'Others',          'more_horiz',    99)
) AS v(slug, name, icon, display_order)
CROSS JOIN public.schools s
WHERE s.slug = 'smith'
ON CONFLICT (school_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  display_order = EXCLUDED.display_order,
  is_active = true;


-- ─── 3. Update seed_school_defaults() RPC ─────────────────────
-- Future schools will get the new default categories.

CREATE OR REPLACE FUNCTION public.seed_school_defaults(p_school_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  -- Default categories
  INSERT INTO public.school_categories (school_id, slug, name, icon, display_order)
  VALUES
    (p_school_id, 'dorm',            'Dorm',            'bed',            1),
    (p_school_id, 'kitchen',         'Kitchen',         'kitchen',        2),
    (p_school_id, 'self_care',       'Self-care',       'spa',            3),
    (p_school_id, 'food',            'Food',            'lunch_dining',   4),
    (p_school_id, 'study_supplies',  'Study Supplies',  'menu_book',      5),
    (p_school_id, 'sports',          'Sports',          'sports_soccer',  6),
    (p_school_id, 'other',           'Others',          'more_horiz',    99)
  ON CONFLICT (school_id, slug) DO NOTHING;

  -- Default conditions
  INSERT INTO public.school_conditions (school_id, slug, name, description, display_order)
  VALUES
    (p_school_id, 'new',      'New',       'Brand new, never used',                1),
    (p_school_id, 'like_new', 'Like New',  'Used once or twice, no visible wear',  2),
    (p_school_id, 'good',     'Good',      'Some signs of use, fully functional',  3),
    (p_school_id, 'fair',     'Fair',      'Noticeable wear, still works',         4),
    (p_school_id, 'poor',     'Poor',      'Heavy wear, may need repair',          5)
  ON CONFLICT (school_id, slug) DO NOTHING;

  -- Default pickup locations
  INSERT INTO public.pickup_locations (school_id, name, display_order)
  VALUES
    (p_school_id, 'Campus Center',              1),
    (p_school_id, 'Main Library',               2),
    (p_school_id, 'Student Union',              3),
    (p_school_id, 'Other (specify in chat)',    99);

  -- Copy global FAQs as school-specific
  INSERT INTO public.faqs (school_id, category, question, answer, display_order)
  SELECT p_school_id, category, question, answer, display_order
  FROM public.faqs
  WHERE school_id IS NULL;
END;
$$;
